// assists
// blocks
// fieldGoalsAttempted
// fieldGoalsMade
// fieldGoalsPercentage
// foulsPersonal
// foulsTechnical
// freeThrowsAttempted
// freeThrowsMade
// freeThrowsPercentage
// minutes
// plusMinusPoints
// points
// reboundsDefensive
// reboundsOffensive
// reboundsTotal
// steals
// threePointersAttempted
// threePointersMade
// threePointersPercentage
// turnovers


// assists
// blocks
// blocksReceived
// fieldGoalsAttempted
// fieldGoalsMade
// fieldGoalsPercentage
// foulsOffensive
// foulsDrawn
// foulsPersonal
// foulsTechnical
// freeThrowsAttempted
// freeThrowsMade
// freeThrowsPercentage
// minus
// minutes
// minutesCalculated
// plus
// plusMinusPoints
// points
// pointsFastBreak
// pointsInThePaint
// pointsSecondChance
// reboundsDefensive
// reboundsOffensive
// reboundsTotal
// steals
// threePointersAttempted
// threePointersMade
// threePointersPercentage
// turnovers
// twoPointersAttempted
// twoPointersMade
// twoPointersPercentage
